spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gps
    username: root
    password: 1234
  #文件上传的配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cwk.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

gps:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 72000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    # 设置jwt签名加密时使用的秘钥
    user-secret-key: itheima
    # 设置jwt过期时间
    user-ttl: 72000000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tCy3WbuVSYVKXSPw6zD
    access-key-secret: 32yafhWWdFlEVRRY9nEaYpXb9V7XAN
    bucket-name: web-tlias-guyu

#支付宝
alipay:
  appId: 9021000136633416
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCuih1f6u20Vk4OSVh85VgANPwDVKgvtC5skVSDPMXYXsG5fG1yJfKA7AX+gy0pnEoaINqIzlAi+Nzc019XZRQQ9Q3skVkjtwHAovI1yv7fNyZzQuPN5BY0u+FcAa0HiKQHoqJOa1Bi05WZ4BKGaqS0/8SfNJN2aUbNWUAqQVpl6LqeBJ8c+HRTEvCPk7MfTHipdqGmPU6MMEINyZbeIhv9FQKJofYjjJaBlVwKdHAooNqg/8ap+wRZLYQI7Jo9w7PfIPeRvi1HuljOmaXv4FoO7uC9Ur9kwCpQF326LeEkuzzEX9EpfwHKgMcMRAgCgUAR2VjCRB2AEBkVN6ZODWiHAgMBAAECggEAW+T57Etblawu8pSpUzDI8Wr0GKjU2DDslFq7/VDc9buGEauyT/wsvrYFvefAunzAAxuzE35UcOVIG7fqJbBhLUBocVphbU1oTc086xeSs2FtDBh2qithiag10eRL/oBxpFd7TwBvVWkDBf4UotK5H1beZdgfn6N0FJ/eCaFY//fzbcHyKVdr2joyAX6Tccvmd5k9yjr5GRU/Bi2SOJnHqcBiG4XpAY7oThli+bBtKG6YuFoQtnrkE5rLzl7NMTtCf8K5h8b3h5WX/xFWpATYsfbYoVz9Z+buC3Ut4LjcjzhJRrd+EkcP8G+y6xe3BKCxHVzm3A4NvGD9jtKW5qpaQQKBgQD732BO+C7PeuioN5ipmgryCLwjQPzWil1ZbKK0W9UfGKSEycOJGplUTCRmfDd7lPOHOwhziwP600qYfk7AGKhD1n7+lCJpwsg0Jq4bJwTWkU1JObsx5IVfIjGhXLh87pJpbx3oEFIAR+BErclCAFUUvwmMHsjDKcLT26E3lknTYQKBgQCxZlIb1/FKb7tg4Z4Y3j1NaiH1jzd3gnaLzfeKMmGFtMVHbyIA7RWUt8Euv/GhFQK4RTRW/0XmOeKJ5V0q0FbcMN2N3knLQsmukRqAIMG4Gg+0E5J1G3lnof/go6dXyot/VSmooIftQIoQQXNvXyyu3aHsuh5W+Ra/QAqPYfss5wKBgQDPT35/wTsWPz38JzaaclYL/TCNe9If6+cF0arh9KwoWiofucodsSz++2UCjb9FEsaXSfmc0JFIBF1jwqKi7iihHY2NkPP6RP5wHl4zrxwGV7ZbTQ9M86DrOsPK4vxeqCcObQ0ak0RLQt3O6ZO7pXZiCxOap0PrjxXzNtUtYaAGQQKBgGKJtmQW78VsCMYIrJudnqmIoXJX6fRtOFHxx2UxFPCC9+308gtXpdwksZ65KYtTM16NukP0qav3TTlReQ3WCdlnHzm1VoIcCBD6MqEnENOlTkG1eW2pJCeHWa062jIupIvHD0vGV5pWdhoPcQJU+GntXAs1WrLuy07SUMtSHoXTAoGBAIK0C49SEV5k+BfGo9qXKzIqNo0lK6k3/0c5GrR+0bZ80ViI1yb0SO/h6J3tNZH7QX4qTdbfNgvzuahAwADN0XncSncOcyKkXFYwyljKQnF383jmnz9DJnjYVaYNbDQmZDe5BV1zK4gYplcAq1TcYiwFvTzmxFyLpGUgJI/813io
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjS9L/duxnZr2QeI7HmUSUIL6Bk7DrcEBf5LWFdWRtmfFG9lbiIMo648Fq8ra0YhNw0GeCpAliVFbl9bA6wCiIpwAa+3v7gfM5UIKtGD1Dvi0n7/WDy9pzTtnP33DcZwnApYMq5PzT5piB9/RYFGw6Bxq5zGf0bfME5my01d869GceRKG1T6hgt/hiAeZzUNbrVRcu1Jw4TSaFbg9yoVt1MC7PSC23PhPHmBS3KjJLdAZsiTWrfHbZmYh2p64kl0EGrrGscf78Cq8b9F50jbcWCW525zlG/jmU28C8ORW37P6B0I4uvuktkRHah1jcOL1xMXriEADwfoNuEo6kaxLswIDAQAB
  notifyUrl: http://wfryi7.natappfree.cc/alipay/notify
  returnUrl:
