spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gps
    username: root
    password: 1234
    #文件上传的配置
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 100MB

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cwk.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true